6.1.6 changelog update
osmlab/atlas-checks pull request #425
Opened 2020-11-17 04:04 UTC by ameliaewatts

### Description:

Updating the changelog with the latest release. 6.1.5

2020-11-17 16:08 UTC, Bentleysb commented
This should be updating CHANGELOG.md, not HISTORY.md

2020-11-18 18:41 UTC, dcastrowa submitted a review, later dismissed

2020-11-18 18:43 UTC, Bentleysb requested changes
This should be updating CHANGELOG.md

2020-11-18 20:11 UTC, ameliaewatts commented
@Bentleysb There we go.

2020-11-18 20:31 UTC, Bentleysb approved these changes

2020-11-18 21:12 UTC, dcastrowa approved these changes

2020-11-18 21:14 UTC, merged