Roundabout min node
osmlab/atlas-checks pull request #476
Opened 2021-01-20 19:00 UTC by brianjor

### Description:

Checks amount of OSM nodes in roundabout are at or above a certain number.
This is a request from our editors to flag roundabouts that are made of fewer than 9 OSM nodes.
We are also checking the angle between the segments of the roundabout.

### Potential Impact:

None

### Unit Test Approach:

Test for roundabouts with fewer than {threshold} OSM nodes
Test for roundabouts with angles greater than {threshold}
Fixed old tests that didn't account for OSM nodes/angles.

### Test Results:

A  note on the FP's: they are all due to Teardrop roundabouts.

|   ISO  | Total Flags | Sampled  | Sampling % | TP  |  FP | False Positive Rate |
|-------|-------------|------------|--------------|-----|-----| ------------------- |
|  ARG  |    51          |      24       |         47%      |  23 |   1  |             4%            |
|  AUS  |    95          |      41        |       49%       |  40 |   1  |             2%            |
|  NZL  |    8            |      8          |       100%     |   7  |   1  |            12%           |
|  SWE |     16         |      16        |       100%     |   12 |   4  |           25%            |

Resolves: #459

2021-01-20 20:28 UTC, vladlemberg requested changes

2021-01-20 20:28 UTC, vladlemberg commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +                if (originalGeometry.size() < this.minNodes && ((Edge) object).isClosed())
isClosed() only applies on particular edge, which is one section of entire roundabout. Please use isClosedWay from  utility.CommonMethods class. this method will be available after merging this [PR](https://github.com/osmlab/atlas-checks/pull/468/).

2021-01-20 22:13 UTC, brianjor commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +                final PolyLine originalGeometry = originalGeometryOptional.get();
Using that method throws the error: 
`org.openstreetmap.atlas.exception.CoreException: Cannot append LINESTRING (-77.0323026 38.9058872, -77.0323992 38.9058287) to LINESTRING (-77.0320559 38.9053612, -77.0315838 38.9055282, -77.0318091 38.9059373, -77.0323026 38.9058872, -77.032367 38.9055198, -77.0320559 38.9053612) - the end and start points do not match.`
For the counterClockwiseRoundaboutRightDrivingWrongEdgesTagTest

2021-01-20 23:34 UTC, vladlemberg commented on src/main/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheck.java
> +                final PolyLine originalGeometry = originalGeometryOptional.get();
thanks Brian, let me check.

2021-01-27 00:33 UTC, ameliaewatts commented
@brianjor Where are we at on this?

2021-01-27 01:11 UTC, brianjor commented
> 
> 
> @brianjor Where are we at on this?

If it LGTY, then it is ready to merge.

2021-01-27 17:41 UTC, Bentleysb commented
@brianjor, this generally looks good to me, but I am slightly concerned by the high FP rate in come countries. The overall rate looks ok though. You mention that the FPs are from teardrop roundabouts. Are they getting flagged due to the node count, the angle check, or both? And do you think there is any possibility the thresholds could be further tuned to reduce that FP rate?

2021-01-27 17:48 UTC, brianjor commented
@Bentleysb 
It is due to the sharp angle that is formed on the "top" of the teardrop. A solution doesn't immediately pop into mind due to most of the TPs also having similar sharp angles.

2021-01-27 18:19 UTC, Bentleysb approved these changes
Ok, I think think there is enough benefit here to move ahead. We will just want to watch for editor feedback on the angle flagging, and perhaps revisit that at a later date if needed.

2021-01-27 19:28 UTC, seancoulter commented
@brianjor Looks good, but I'm also curious about the Teardrop Roundabouts. do you have any OSM examples of them?

2021-01-27 20:45 UTC, brianjor commented
@seancoulter
Teardrop roundabout FPs:
https://www.openstreetmap.org/way/188814094
https://www.openstreetmap.org/way/173498494

Roundabout with a sharp angle TP:
https://www.openstreetmap.org/way/460143240

2021-01-27 21:16 UTC, seancoulter commented
> @seancoulter
> Teardrop roundabout FPs:
> https://www.openstreetmap.org/way/188814094
> https://www.openstreetmap.org/way/173498494
> 
> Roundabout with a sharp angle TP:
> https://www.openstreetmap.org/way/460143240

Thanks, yeah this looks like it could get complicated. For these we may want to check the entry/exit vertex of the teardrop and check if the in (leaving roundabout) and out (entering roundabout) edges have sufficiently similar headings, with one heading reversed. We could also throw in a length check on those edges to avoid validating sharp angles. But I'm fine with this being a future investigation

2021-01-27 21:48 UTC, ameliaewatts commented
@seancoulter @brianjor Good to go then?

2021-01-27 22:01 UTC, merged

2021-01-28 02:35 UTC, vladlemberg commented
@seancoulter, @brianjor, @ameliaewatts, @Bentleysb
My new PR didn't pass CI integration because of this change. It basically didn't pass the old UNIT tests. I believe its happened because we were in transition from Travis. 
**Example:** 
https://github.com/osmlab/atlas-checks/blob/3e3d0fd82f348c5f90c16b32f6e2d1b4bcae3fcd/src/test/java/org/openstreetmap/atlas/checks/validation/linear/edges/MalformedRoundaboutCheckTest.java#L123.

its not passing because this roundabout has less than 9 nodes and has sharp angle. 

@brianjor, i guess you need to modify all previous Unit tests so they don't fall into new logic. 

@ameliaewatts, do we need to revert this change ? 

@brianjor, I fixed buildingOriginalOsmGeometry issue with reversed Edges. https://github.com/osmlab/atlas-checks/pull/484
so I guess you can safely remove try/catch. Thanks for finding this issue!